import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar .env desde la raíz del proyecto
load_dotenv(Path(__file__).parent.parent / ".env")

BCCH_USER = os.getenv("BCCH_USER")
BCCH_PASS = os.getenv("BCCH_PASS")
BCCH_API_URL = "https://si3.bcentral.cl/SieteRestWS/SieteRestWS.ashx"

DB_PATH = Path(__file__).parent / "bloomberg_chile.db"

# Rate limiting: max 3 req/seg (API permite 5, dejamos margen)
RATE_LIMIT_DELAY = 0.35  # segundos entre requests

# Catálogo de series — cada una confirmada funcionando contra la API
SERIES_CATALOG = {
    "tpm": {
        "bcch_id": "F022.TPM.TIN.D001.NO.Z.D",
        "name_es": "Tasa de Política Monetaria (TPM)",
        "name_en": "Monetary Policy Rate (MPR)",
        "frequency": "DAILY",
        "unit": "porcentaje",
        "history_start": "2001-01-01",
    },
    "usd_clp": {
        "bcch_id": "F073.TCO.PRE.Z.D",
        "name_es": "Tipo de Cambio Dólar Observado",
        "name_en": "Observed USD/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_usd",
        "history_start": "2000-01-01",
    },
    "ipsa": {
        "bcch_id": "F013.IBC.IND.N.7.LAC.CL.CLP.BLO.D",
        "name_es": "IPSA - Índice de Precios Selectivo de Acciones",
        "name_en": "IPSA - Selective Stock Price Index",
        "frequency": "DAILY",
        "unit": "puntos",
        "history_start": "2000-01-01",
    },
    "uf": {
        "bcch_id": "F073.UFF.PRE.Z.D",
        "name_es": "Unidad de Fomento (UF)",
        "name_en": "Unidad de Fomento (UF)",
        "frequency": "DAILY",
        "unit": "clp",
        "history_start": "2000-01-01",
    },
    "imacec": {
        "bcch_id": "F032.IMC.IND.Z.Z.EP18.Z.Z.0.M",
        "name_es": "IMACEC Empalmado (Base 2018=100)",
        "name_en": "IMACEC Spliced Index (Base 2018=100)",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2000-01-01",
    },
    "desempleo": {
        "bcch_id": "F049.DES.TAS.INE9.10.M",
        "name_es": "Tasa de Desocupación",
        "name_en": "Unemployment Rate",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2000-01-01",
    },
    "ipc_var": {
        "bcch_id": "F074.IPC.VAR.Z.Z.C.M",
        "name_es": "IPC Variación Mensual",
        "name_en": "CPI Monthly Variation",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2000-01-01",
    },
    "base_monetaria": {
        "bcch_id": "F021.BMO.STO.N.CLP.0.M",
        "name_es": "Base Monetaria (Emisión)",
        "name_en": "Monetary Base",
        "frequency": "MONTHLY",
        "unit": "miles_millones_clp",
        "history_start": "2000-01-01",
    },
    "reservas_intl": {
        "bcch_id": "F062.A5.STO.PF.USD.M",
        "name_es": "Reservas Internacionales",
        "name_en": "International Reserves",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "export_mineras": {
        "bcch_id": "F068.B1.FLU.A.0.C.N.Z.Z.Z.Z.6.0.M",
        "name_es": "Exportaciones FOB Mineras",
        "name_en": "Mining FOB Exports",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "deuda_pib": {
        "bcch_id": "F051.D7.PPB.C.Z.Z.T",
        "name_es": "Deuda Bruta Gobierno Central (% PIB)",
        "name_en": "Gross Government Debt (% GDP)",
        "frequency": "QUARTERLY",
        "unit": "porcentaje_pib",
        "history_start": "2000-01-01",
    },
    "cuenta_corriente": {
        "bcch_id": "F068.A.FLU.Z.0.S.N.Z.Z.Z.Z.6.0.T",
        "name_es": "Cuenta Corriente",
        "name_en": "Current Account",
        "frequency": "QUARTERLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    # --- Fase 3: Cobre ---
    "cobre": {
        "bcch_id": "F019.PPB.PRE.100.D",
        "name_es": "Precio Cobre BML",
        "name_en": "Copper Price BML",
        "frequency": "DAILY",
        "unit": "usd_lb",
        "history_start": "2000-01-01",
    },
    "cobre_export": {
        "bcch_id": "F068.B1.FLU.A1.0.C.N.Z.Z.Z.Z.6.0.M",
        "name_es": "Exportaciones de Cobre",
        "name_en": "Copper Exports",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    # --- Fase 3: Bonos (Yield Curve) ---
    "bcp_2y": {
        "bcch_id": "F022.BCLP.TIS.AN02.NO.Z.D",
        "name_es": "BCP 2 Años (Mercado Secundario)",
        "name_en": "BCP 2Y Secondary Market Rate",
        "frequency": "DAILY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "bcp_5y": {
        "bcch_id": "F022.BCLP.TIS.AN05.NO.Z.D",
        "name_es": "BCP 5 Años (Mercado Secundario)",
        "name_en": "BCP 5Y Secondary Market Rate",
        "frequency": "DAILY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "bcp_10y": {
        "bcch_id": "F022.BCLP.TIS.AN10.NO.Z.D",
        "name_es": "BCP 10 Años (Mercado Secundario)",
        "name_en": "BCP 10Y Secondary Market Rate",
        "frequency": "DAILY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    # --- Fase 3: FX Latam ---
    "eur_clp": {
        "bcch_id": "F072.CLP.EUR.N.O.D",
        "name_es": "Tipo de Cambio EUR/CLP",
        "name_en": "EUR/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_eur",
        "history_start": "2000-01-01",
    },
    "cny_clp": {
        "bcch_id": "F072.CLP.CNY.N.O.D",
        "name_es": "Tipo de Cambio CNY/CLP",
        "name_en": "CNY/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_cny",
        "history_start": "2005-01-01",
    },
    "brl_clp": {
        "bcch_id": "F072.CLP.BRL.N.O.D",
        "name_es": "Tipo de Cambio BRL/CLP",
        "name_en": "BRL/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_brl",
        "history_start": "2000-01-01",
    },
    "ars_clp": {
        "bcch_id": "F072.CLP.ARS.N.O.D",
        "name_es": "Tipo de Cambio ARS/CLP",
        "name_en": "ARS/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_ars",
        "history_start": "2000-01-01",
    },
    "cop_clp": {
        "bcch_id": "F072.CLP.COP.N.O.D",
        "name_es": "Tipo de Cambio COP/CLP",
        "name_en": "COP/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_cop",
        "history_start": "2000-01-01",
    },
    "pen_clp": {
        "bcch_id": "F072.CLP.PEN.N.O.D",
        "name_es": "Tipo de Cambio PEN/CLP",
        "name_en": "PEN/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_pen",
        "history_start": "2000-01-01",
    },
    "mxn_clp": {
        "bcch_id": "F072.CLP.MXN.N.O.D",
        "name_es": "Tipo de Cambio MXN/CLP",
        "name_en": "MXN/CLP Exchange Rate",
        "frequency": "DAILY",
        "unit": "clp_por_mxn",
        "history_start": "2000-01-01",
    },
    # --- Fase 3: Expectativas (EOF) ---
    "eof_5y_2m": {
        "bcch_id": "F089.BP5.TAS.13.M",
        "name_es": "EOF BCP5 Horizonte 2 Meses",
        "name_en": "EOF BCP5 2-Month Horizon",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "eof_5y_11m": {
        "bcch_id": "F089.BP5.TAS.14.M",
        "name_es": "EOF BCP5 Horizonte 11 Meses",
        "name_en": "EOF BCP5 11-Month Horizon",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "eof_5y_23m": {
        "bcch_id": "F089.BP5.TAS.15.M",
        "name_es": "EOF BCP5 Horizonte 23 Meses",
        "name_en": "EOF BCP5 23-Month Horizon",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    # ── Fase 4: Precios desagregados ──────────────────
    "ipc_anual": {
        "bcch_id": "G073.IPC.V12.2023.M",
        "name_es": "IPC Variación 12 Meses (Anual)",
        "name_en": "CPI Year-over-Year Variation",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2000-01-01",
    },
    "ipc_alimentos": {
        "bcch_id": "F074.IPCA.VAR.Z.2023.C.M",
        "name_es": "IPC Alimentos Variación Mensual",
        "name_en": "CPI Food Monthly Variation",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2010-01-01",
    },
    "ipc_vivienda": {
        "bcch_id": "F074.IPCVIV.VAR.Z.2023.C.M",
        "name_es": "IPC Vivienda Variación Mensual",
        "name_en": "CPI Housing Monthly Variation",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2010-01-01",
    },
    "ipc_transables": {
        "bcch_id": "F074.IPCT.VAR.Z.2023.C.M",
        "name_es": "IPC Transables Variación Mensual",
        "name_en": "CPI Tradables Monthly Variation",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2010-01-01",
    },
    # ── Fase 4: Trabajo y sueldos ─────────────────────
    "remuneraciones_nom": {
        "bcch_id": "F049.RMU.IND.HIST.81.M",
        "name_es": "Índice de Remuneraciones Nominales",
        "name_en": "Nominal Wage Index",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2000-01-01",
    },
    "remuneraciones_real": {
        "bcch_id": "G049.RMM.IND.INE23.R.M",
        "name_es": "Índice de Remuneraciones Reales",
        "name_en": "Real Wage Index",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2010-01-01",
    },
    # ── Fase 4: Confianza y percepción ────────────────
    "icc": {
        "bcch_id": "F089.ICC.IND.B1.M",
        "name_es": "Índice Confianza Consumidor (IPSOS ICC)",
        "name_en": "Consumer Confidence Index (IPSOS ICC)",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2003-01-01",
    },
    "ipec": {
        "bcch_id": "F089.IPE.IND.75M2.M",
        "name_es": "Índice Percepción Económica (IPEC)",
        "name_en": "Economic Perception Index (IPEC)",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2003-01-01",
    },
    "imce": {
        "bcch_id": "G089.IME.IND.A0.M",
        "name_es": "IMCE Total (Confianza Empresarial)",
        "name_en": "Business Confidence Index (IMCE)",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "2004-01-01",
    },
    # ── Fase 4: Expectativas EOF directas ─────────────
    "eof_tpm_1m": {
        "bcch_id": "F089.TPM.TAS.11.M",
        "name_es": "EOF TPM Esperada en el Mes",
        "name_en": "EOF Expected MPR This Month",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "eof_tpm_11m": {
        "bcch_id": "F089.TPM.TAS.14.M",
        "name_es": "EOF TPM Esperada 11 Meses",
        "name_en": "EOF Expected MPR 11-Month",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "eof_tpm_23m": {
        "bcch_id": "F089.TPM.TAS.15.M",
        "name_es": "EOF TPM Esperada 23 Meses",
        "name_en": "EOF Expected MPR 23-Month",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2005-01-01",
    },
    "eof_pib_2026": {
        "bcch_id": "F089.PIB.V12.2026.M",
        "name_es": "Expectativa Crecimiento PIB 2026",
        "name_en": "GDP Growth Expectation 2026",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2024-01-01",
    },
    "eof_pib_2027": {
        "bcch_id": "F089.PIB.V12.2027.M",
        "name_es": "Expectativa Crecimiento PIB 2027",
        "name_en": "GDP Growth Expectation 2027",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2024-01-01",
    },
    # ── Fase 4: Comercio exterior ─────────────────────
    "export_total": {
        "bcch_id": "F068.B1.FLU.Z.0.C.N.Z.Z.Z.Z.6.0.M",
        "name_es": "Exportaciones Totales FOB",
        "name_en": "Total FOB Exports",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "import_total": {
        "bcch_id": "F068.B1.FLU.Z.0.M.N.0.Z.Z.Z.6.0.M",
        "name_es": "Importaciones Totales CIF",
        "name_en": "Total CIF Imports",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "balanza_comercial": {
        "bcch_id": "F068.B1.VAR.T0.0.S.N.Z.Z.Z.Z.6.0.M",
        "name_es": "Saldo Balanza Comercial",
        "name_en": "Trade Balance",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "export_litio": {
        "bcch_id": "F068.B1.FLU.A8.0.C.N.Z.Z.Z.Z.6.0.M",
        "name_es": "Exportaciones Carbonato de Litio",
        "name_en": "Lithium Carbonate Exports",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2010-01-01",
    },
    # ── Fase 4: Crédito y sistema financiero ──────────
    "colocaciones": {
        "bcch_id": "F022.CEF.STO.Z.Z.CLP.M",
        "name_es": "Colocaciones Efectivas Totales en CLP",
        "name_en": "Total Effective Loans in CLP",
        "frequency": "MONTHLY",
        "unit": "miles_millones_clp",
        "history_start": "2000-01-01",
    },
    "spread_bancario": {
        "bcch_id": "F022.SBR.TIN.AN01.NO.Z.M",
        "name_es": "Spread Bruto Bancario 90d-1Y",
        "name_en": "Banking Gross Spread 90d-1Y",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2000-01-01",
    },
    "tasa_captacion": {
        "bcch_id": "F022.CAP.TIN.AN01.NO.Z.M",
        "name_es": "Tasa Captación 90d-1Y Pesos",
        "name_en": "Deposit Rate 90d-1Y CLP",
        "frequency": "MONTHLY",
        "unit": "porcentaje",
        "history_start": "2000-01-01",
    },
    # ── Fase 4: Agregados monetarios ──────────────────
    "m1": {
        "bcch_id": "F021.M1.STO.N.CLP.5.M",
        "name_es": "Agregado Monetario M1 (Saldos)",
        "name_en": "M1 Money Supply (Balances)",
        "frequency": "MONTHLY",
        "unit": "miles_millones_clp",
        "history_start": "2000-01-01",
    },
    "m2": {
        "bcch_id": "F021.M2.STO.N.CLP.5.M",
        "name_es": "Agregado Monetario M2 (Saldos)",
        "name_en": "M2 Money Supply (Balances)",
        "frequency": "MONTHLY",
        "unit": "miles_millones_clp",
        "history_start": "2000-01-01",
    },
    # ── Fase 4: Tipo de cambio real ───────────────────
    "tcr": {
        "bcch_id": "F073.TCR.IND.199101.M",
        "name_es": "Índice Tipo de Cambio Real (TCR)",
        "name_en": "Real Exchange Rate Index (REER)",
        "frequency": "MONTHLY",
        "unit": "indice",
        "history_start": "1991-01-01",
    },
    # ── Fase 4: Deuda externa ─────────────────────────
    "deuda_ext_cp": {
        "bcch_id": "F068.T6.STO.Z.Z.S.P.Z.O.Z.Z.6.0.M",
        "name_es": "Deuda Externa Corto Plazo",
        "name_en": "Short-Term External Debt",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
    "deuda_ext_lp": {
        "bcch_id": "F068.T6.STO.Z.Z.S.P.Z.P.Z.Z.6.0.M",
        "name_es": "Deuda Externa Largo Plazo",
        "name_en": "Long-Term External Debt",
        "frequency": "MONTHLY",
        "unit": "millones_usd",
        "history_start": "2000-01-01",
    },
}
